name: Deploy to Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: write
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  pages:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "16"
      - name: Install
        run: npm ci
      - name: Clone
        run: git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_ACTOR}/${GITHUB_ACTOR}.github.io.git" --branch master --single-branch ./build
      - name: Build
        run: npm run build:prod
      - name: Push
        run: |
          git add ./build -f
          git commit -m "${GITHUB_REPOSITORY} $(date +'%Y-%m-%d %H:%M:%S')"
          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_ACTOR}/${GITHUB_ACTOR}.github.io.git master
